# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='', max_length=5, verbose_name='\u673a\u6784\u7c7b\u522b'),
            preserve_default=False,
        ),
    ]
