# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-08 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570'),
        ),
        migrations.AddField(
            model_name='organization',
            name='student_nums',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gx', '\u9ad8\u6821'), ('gr', '\u4e2a\u4eba')], default='pxjg', max_length=5, verbose_name='\u673a\u6784\u7c7b\u522b'),
        ),
    ]
