# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170108_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.TextField(default='', verbose_name='\u57ce\u5e02\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9'),
        ),
    ]
