# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.SmallIntegerField(default=18, verbose_name='\u5e74\u9f84'),
        ),
    ]
