# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-25 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170117_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tag',
            field=models.CharField(default='\u4e16\u754c\u540d\u6821', max_length=10, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
