# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomments',
            old_name='cource',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='usercourse',
            old_name='cource',
            new_name='course',
        ),
    ]
