# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-11 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170103_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (2, '\u673a\u6784'), (3, '\u8bb2\u5e08')], default=1, max_length=1, verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
