# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(max_length=200, upload_to='course/resource/%Y/%m', verbose_name='\u4e0b\u8f7d\u5730\u5740'),
        ),
    ]
