# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170110_0718'),
        ('courses', '0002_auto_20170103_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization', verbose_name='\u8bfe\u7a0b\u673a\u6784'),
        ),
    ]
