# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170112_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.IntegerField(choices=[(1, '\u524d\u7aef\u5f00\u53d1'), (2, '\u540e\u7aef\u5f00\u53d1')], default=1, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
