# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='\u8bbf\u95ee\u5730\u5740'),
        ),
    ]
