# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-31 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161231_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=10, verbose_name='\u6027\u522b'),
        ),
    ]
