# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-05 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170105_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u6635\u79f0'),
        ),
    ]
